# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "EspruinoBuildEnvironment"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.synced_folder "../", "/Espruino"

  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--memory", "2048"]
    #vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    vb.customize ["modifyvm", :id, "--usb", "on"]
    #vb.customize ["usbfilter", "add", "0", "--target", :id, "--name", "stm32-stlink", "--vendorid", "0x0483", "--productid", "0x3748"]
    vb.customize ["usbfilter", "add", "1", "--target", :id, "--name", "stm32-vcom", "--vendorid", "0x0483", "--productid", "0x5740"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "EspruinoBuildEnvironment"
  end

  config.vm.provision :shell, :path => "setupEspruinoBuild.sh"
end
