#
# Automatically generated by blueprint(7).  Edit at your own risk.
#
directory('/etc/apt/apt.conf.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/apt/apt.conf.d/00CDMountPoint') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/apt/apt.conf.d/00CDMountPoint'
end
directory('/etc/apt/apt.conf.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/apt/apt.conf.d/00aptitude') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/apt/apt.conf.d/00aptitude'
end
directory('/etc/apt') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/apt/sources.list') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/apt/sources.list'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
link('/etc/blkid.tab') do
  group 'root'
  owner 'root'
  to '/dev/.blkid.tab'
end
directory('/etc/default') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/default/console-setup') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/default/console-setup'
end
directory('/etc/default') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/default/keyboard') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/default/keyboard'
end
directory('/etc/default') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/default/locale') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/default/locale'
end
directory('/etc/default') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/default/nfs-common') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/default/nfs-common'
end
directory('/etc/default') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/default/ntfs-3g') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/default/ntfs-3g'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/hosts') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/hosts'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/idmapd.conf') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/idmapd.conf'
end
directory('/etc/init.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/init.d/vboxadd') do
  backup false
  group 'root'
  mode '0755'
  owner 'root'
  source 'etc/init.d/vboxadd'
end
directory('/etc/init.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/init.d/vboxadd-service') do
  backup false
  group 'root'
  mode '0755'
  owner 'root'
  source 'etc/init.d/vboxadd-service'
end
directory('/etc/init.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/init.d/vboxadd-x11') do
  backup false
  group 'root'
  mode '0755'
  owner 'root'
  source 'etc/init.d/vboxadd-x11'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/motd.tail') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/motd.tail'
end
directory('/etc/profile.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/profile.d/vagrant_ruby.sh') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/profile.d/vagrant_ruby.sh'
end
directory('/etc/resolvconf/resolv.conf.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/resolvconf/resolv.conf.d/original') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/resolvconf/resolv.conf.d/original'
end
directory('/etc') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/shells') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/shells'
end
directory('/etc/ssh') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/ssh/sshd_config') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/ssh/sshd_config'
end
directory('/etc/systemd/system/multi-user.target.wants') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
link('/etc/systemd/system/multi-user.target.wants/rsyslog.service') do
  group 'root'
  owner 'root'
  to '/lib/systemd/system/rsyslog.service'
end
directory('/etc/udev/rules.d') do
  group 'root'
  mode '0755'
  owner 'root'
  recursive true
end
cookbook_file('/etc/udev/rules.d/60-vboxadd.rules') do
  backup false
  group 'root'
  mode '0644'
  owner 'root'
  source 'etc/udev/rules.d/60-vboxadd.rules'
end
execute('apt-get -q update')
package('autoconf') { version '2.68-1ubuntu2' }
package('automake') { version '1:1.11.3-1ubuntu2' }
package('autopoint') { version '0.18.1.1-5ubuntu3' }
package('autotools-dev') { version '20120210.1ubuntu1' }
package('binutils') { version '2.22-6ubuntu1' }
package('bison') { version '1:2.5.dfsg-2.1' }
package('build-essential') { version '11.5ubuntu2.1' }
package('cpp') { version '4:4.6.3-1ubuntu5' }
package('cpp-4.6') { version '4.6.3-1ubuntu5' }
package('curl') { version '7.22.0-3ubuntu4.3' }
package('dpkg-dev') { version '1.16.1.2ubuntu7.1' }
package('fakeroot') { version '1.18.2-1' }
package('flex') { version '2.5.35-10ubuntu3' }
package('g++') { version '4:4.6.3-1ubuntu5' }
package('g++-4.6') { version '4.6.3-1ubuntu5' }
package('gcc') { version '4:4.6.3-1ubuntu5' }
package('gcc-4.6') { version '4.6.3-1ubuntu5' }
package('git') { version '1:1.7.9.5-1' }
package('git-man') { version '1:1.7.9.5-1' }
package('libalgorithm-diff-perl') { version '1.19.02-2' }
package('libalgorithm-diff-xs-perl') { version '0.04-2build2' }
package('libalgorithm-merge-perl') { version '0.08-2' }
package('libbison-dev') { version '1:2.5.dfsg-2.1' }
package('libc-dev-bin') { version '2.15-0ubuntu10' }
package('libc6-dev') { version '2.15-0ubuntu10' }
package('libcurl3') { version '7.22.0-3ubuntu4.3' }
package('libdevmapper-event1.02.1') { version '2:1.02.48-4ubuntu7' }
package('libdpkg-perl') { version '1.16.1.2ubuntu7.1' }
package('libelf-dev') { version '0.152-1ubuntu3' }
package('liberror-perl') { version '0.17-1' }
package('libfl-dev') { version '2.5.35-10ubuntu3' }
package('libgmp-dev') { version '2:5.0.2+dfsg-2ubuntu1' }
package('libgmp10') { version '2:5.0.2+dfsg-2ubuntu1' }
package('libgmp3-dev') { version '2:5.0.2+dfsg-2ubuntu1' }
package('libgmpxx4ldbl') { version '2:5.0.2+dfsg-2ubuntu1' }
package('libgomp1') { version '4.6.3-1ubuntu5' }
package('libltdl-dev') { version '2.4.2-1ubuntu1' }
package('libltdl7') { version '2.4.2-1ubuntu1' }
package('libmpc-dev') { version '0.9-4' }
package('libmpc2') { version '0.9-4' }
package('libmpfr-dev') { version '3.1.0-3ubuntu2' }
package('libmpfr4') { version '3.1.0-3ubuntu2' }
package('libncurses5-dev') { version '5.9-4' }
package('libopts25') { version '1:5.12-0.1ubuntu1' }
package('libquadmath0') { version '4.6.3-1ubuntu5' }
package('libreadline-dev') { version '6.2-8' }
package('libreadline6-dev') { version '6.2-8' }
package('libssl-dev') { version '1.0.1-4ubuntu5.5' }
package('libssl-doc') { version '1.0.1-4ubuntu5.5' }
package('libstdc++6-4.6-dev') { version '4.6.3-1ubuntu5' }
package('libtinfo-dev') { version '5.9-4' }
package('libtool') { version '2.4.2-1ubuntu1' }
package('libusb-1.0-0-dev') { version '2:1.0.9~rc3-2ubuntu1' }
package('linux-libc-dev') { version '3.2.0-30.48' }
package('lvm2') { version '2.02.66-4ubuntu7' }
package('manpages-dev') { version '3.35-0.1ubuntu1' }
package('ntp') { version '1:4.2.6.p3+dfsg-1ubuntu3.1' }
package('openssh-server') { version '1:5.9p1-5ubuntu1' }
package('pkg-config') { version '0.26-1ubuntu1' }
package('python-pip') { version '1.0-1build1' }
package('python-pkg-resources') { version '0.6.24-1ubuntu1' }
package('python-setuptools') { version '0.6.24-1ubuntu1' }
package('screen') { version '4.0.3-14ubuntu8' }
package('ssh-import-id') { version '2.10-0ubuntu1' }
package('unzip') { version '6.0-4ubuntu1' }
package('watershed') { version '6' }
package('zlib1g-dev') { version '1:1.2.3.4.dfsg-3ubuntu4' }
execute('pip install blueprint==3.4.2')
service('ntp') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/default/nfs-common]', 'cookbook_file[/etc/default/locale]', 'cookbook_file[/etc/default/console-setup]', 'cookbook_file[/etc/default/keyboard]', 'cookbook_file[/etc/default/ntfs-3g]', 'package[ntp]')
end
service('ssh') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/default/nfs-common]', 'cookbook_file[/etc/default/locale]', 'cookbook_file[/etc/default/console-setup]', 'cookbook_file[/etc/default/keyboard]', 'cookbook_file[/etc/default/ntfs-3g]', 'package[openssh-server]')
end
service('vboxadd') do
  action [:enable, :start]
  subscribes :restart, resources('cookbook_file[/etc/udev/rules.d/60-vboxadd.rules]')
end
service('vboxadd-service') do
  action [:enable, :start]
  subscribes :restart, resources()
end
service('vboxadd-x11') do
  action [:enable, :start]
  subscribes :restart, resources()
end
